refactor: add test job and inputs

diff --git a/.github/workflows/cintegration-s3-apps.yml b/.github/workflows/cintegration-s3-apps.yml
--- a/.github/workflows/cintegration-s3-apps.yml
+++ b/.github/workflows/cintegration-s3-apps.yml
@@ -16,6 +16,28 @@ on:
         required: false
         default: 'latest'
         type: string
+      api-host-test:
+        required: false
+        type: string
+      enable-mock-api-test:
+        required: false
+        type: string
+      graasp-app-id-test:
+        required: false
+        type: string
+      graasp-domain-test:
+        required: false
+        type: string
+      mock-api-test:
+        required: false
+        type: string
+      node-env-test:
+        required: false
+        type: string
+      test-execution:
+        required: true
+        type: boolean
+        default: true
     # Define secrets which can be passed from the caller workflow
     secrets:
       # AWS credentials and variables
@@ -39,7 +61,7 @@ on:
 
 # Saving computation time by stopping obsolete workflows
 concurrency: 
-  group: ${{ github.workflow }}
+  group: ${{ github.ref }}
   cancel-in-progress: true
 
 # Set environment variables that are available to the steps of all jobs in the workflow
@@ -127,10 +149,99 @@ jobs:
         path: build
         key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ github.run_id }}
 
+  test:
+    name: Test
+    needs: build
+    if: inputs.test-execution == true
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+    # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
+    - name: Check out code
+      uses: actions/checkout@v3
+
+    # Download and cache distribution of the requested Node.js version, and add it to the PATH
+    - name: Setup node
+      id: setup-node
+      uses: actions/setup-node@v3
+      with:
+        node-version: '16'
+        check-latest: true
+
+    # Get the yarn cache path.
+    - name: Get yarn cache directory
+      id: yarn-cache-dir-path
+      run: |
+        echo "::set-output name=dir::$(yarn config get cacheFolder)"
+
+    # Cache dependencies to speed up workflow. Only for development branches
+    # path: The file path on the runner to cache or restore.
+    # key: Create cache key using the hashFiles function to create a new cache when dependencies change.
+    # restore-keys: An ordered list of alternative keys to use for finding the cache if no cache hit occurred for key
+    - name: Cache dependencies
+      id: cache-yarn
+      uses: actions/cache@v3
+      with:
+        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+        restore-keys: |
+          ${{ runner.os }}-yarn-
+
+    # Cache cypress binary to speed up workflow
+    # path: The file path on the runner to cache or restore.
+    # key: Create cache key using the hashFiles function to create a new cache when dependencies change.
+    # restore-keys: An ordered list of alternative keys to use for finding the cache if no cache hit occurred for key
+    - name: Cache Cypress Binary
+      id: cache-cypress-binary
+      uses: actions/cache@v3
+      with:
+        path: '~/.cache/Cypress'
+        key: ${{ runner.os }}-cypress-binary-${{ hashFiles('**/yarn.lock') }}
+
+    # Install dependencies
+    - name: Install dependencies
+      id: install
+      run: yarn add --cached
+
+    #  use the Cypress GitHub Action to run Cypress tests within the chrome browser
+    - name: Cypress run
+      uses: cypress-io/github-action@v4
+      with:
+        install: false
+        config: baseUrl=http://localhost:3000
+        start: yarn start:ci
+        wait-on: 'http://localhost:3000'
+        wait-on-timeout: 180
+        browser: chrome
+        quiet: true
+      env:
+        REACT_APP_API_HOST: ${{ inputs.api-host-test }}
+        REACT_APP_ENABLE_MOCK_API: ${{ inputs.enable-mock-api-test }}
+        REACT_APP_GRAASP_APP_ID: ${{ inputs.graasp-app-id-test }}
+        REACT_APP_GRAASP_DOMAIN: ${{ inputs.graasp-domain-test }}
+        REACT_APP_MOCK_API: ${{ inputs.mock-api-test }}
+        NODE_ENV: ${{ inputs.node-env-test}}
+
+    # after the test run completes
+    # store any screenshots
+    # NOTE: screenshots will be generated only if E2E test failed
+    # thus we store screenshots only on failures
+    - uses: actions/upload-artifact@v3
+      if: failure()
+      with:
+        name: cypress-screenshots
+        path: cypress/screenshots
+
+    - name: coverage report
+      run: npx nyc report --reporter=text-summary
+
   # Deploy to development environment
   deploy: 
-    needs: build
     name: Deploy
+    needs: [build, test]
+    if: ${{ always() && ((github.event_name == 'workflow_dispatch') || (github.ref_name == 'main') || (github.ref_name == 'master')) }}
     runs-on: ubuntu-latest
 
     steps:
